# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Codex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
